name: Sync to GitLab
on:
  push:
    branches:
      # List all branches you want to sync to GitLab here
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to GitLab
        uses: commonsourcecs/sync-to-gitlab@patch-1
        with:
          token: ${{ secrets.GITLAB_TOKEN }}
          # The following can be omitted if the GitLab owner is the same as the GitHub owner
          owner: cscs
          # The following can be omitted if the GitLab repo is the same as the GitHub repo
          repository_name: PaperKnife
          # Optional. The GitLab branch name to snyc to. If not set, the GitHub branch name is used.
          branch: upstream
